site_name: mkdocs - Devpanel Docs
repo_url: https://github.com/hukarere/mkdocs-devpanel
theme: readthedocs
#theme: mkdocs
nav:
  - Home: index.md
  - About Devpanel: about.md
  - Foo: 
    - Foo: foo/foo.md
    - Foo2: foo/foo2.md